### ISSUE TITLE
Computed properties break dues to logger operations now being async

### ISSUE THREAD

**Issue by ajmas** [dev-tavern/vue-logger-plugin#26]
The switch to using promises in recent versions creates a problem, since now any function or method that logs now has to become a promise, event if nothing else in the function is inherently async. 

If any of those function were being used by a computed property, then they can no longer be used, due to computed properties not supporting async operations.

Can the logging operations be implemented without being async or have an synchronous counter-part?

Edit: Just looked at the source and see this has been this way for a while, but a typescript update in our environment now requires us to mark any function that uses async call async. Would there be any value in providing a simple logging function that does not use the hooks?

**Comment by joshuagamble** [comment]
Since the intent of the changes in v2.2.0 were only to support asynchronous hook operations, I don't see a true need for the logging functions (log, error, warn, info debug) to return a promise themselves.  I also don't imagine anyone actually wanting to await the completion of the logging function anyway.

I've been able to rewrite these logging functions so that they no longer return a promise and the logger can handle the hook operation promises internally.  In my quick testing, this appears to work fine using both async and non-async hook operations, and it allows for compliance with the no-floating-promise eslint rule.

Will provide further update soon.

**Comment by joshuagamble** [comment]
The version 2.2.2 contains the changes which should resolve this issue.

You may try it out by installing the package using the `next` tag:
```
npm i vue-logger-plugin@next
````

Once I've completed a bit more testing, I'll be merging the PR which will automatically close this issue.  If you are still experiencing the issue with the new version, please let me know.  Thanks.

**Comment by ajmas** [comment]
I was only just able to try it out and this solve things. Thanks
